/// Flutter icons PawsHunger
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PawsHunger
///      fonts:
///       - asset: fonts/PawsHunger.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PawsHunger {
  PawsHunger._();

  static const _kFontFam = 'PawsHunger';
  static const String? _kFontPkg = null;

  static const IconData paws_hunger = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
